### ISSUE TITLE
Crashes

### ISSUE THREAD

**Issue by dremonq** [Vili1/Among-us-Free-Chat-unlocker#11]
When I run the unlocker while among us is open some pop up with among us logo appears and then crashes

**Comment by Vili1** [comment]
which version do u have

**Comment by MandiYang** [comment]
Same problem here, 2021.5.10s

**Comment by MandiYang** [comment]
But I use wine cuz I am in linux

**Comment by dremonq** [comment]
> which version do u have

nvm I fixed it lol

**Comment by Vili1** [comment]
@MandiYang yeh it wouldnt work on linux trought wine because wine isolates the processes and the program that ive made wont be able to find among us

**Comment by Vili1** [comment]
@MandiYang you will have better luck using a VM like virtual box or VMPlayer

**Comment by MandiYang** [comment]
The program actually founded among us but then amog us crash handler executed

**Comment by Vili1** [comment]
@MandiYang can u send me a screen shot or something

**Comment by MandiYang** [comment]
Crash log: 
[backtrace.txt](https://github.com/Vili1/Among-us-Free-Chat-unlocker/files/6527746/backtrace.txt)

Screenshot:
![Screenshot from 2021-05-23 10-10-36](https://user-images.githubusercontent.com/64307609/119252994-5edaca80-bbaf-11eb-994d-37d25e66d116.png)

**Comment by Vili1** [comment]
from what i can see in the log wine freaks out when the program tries to read from the process , maybe u should try to change the read and write access on the program using the terminal by going it no the directory where the file is saved with the cd command and then chmod a+x and the file name which in the later relase is "among_us_free_chat.exe
"  , but i doubt that this will work , u will have better luck if u try that in a virtual machien :/

**Comment by Vili1** [comment]
im not really sure how wine exactly works to be hones but it tranlates some of the windows api calls to linux and linux handles stuff in ram differently than windows

**Comment by MandiYang** [comment]
It worked in previous version but not in 2021.5.10s

**Comment by Vili1** [comment]
im not sure , i cant really help you

**Comment by Vili1** [comment]
@MandiYang on second tought i did some clean up in the last version , so if u have an discord add me there and i can make u a custom build without the code cleanup and we can try that if its going to works and stuff my discord is Vili#2690
