### ISSUE TITLE
Please give the user the option to download a zip file of the program, and the program itself.

### ISSUE THREAD

**Issue by MainframeSuper** [Vili1/Among-us-Free-Chat-unlocker#12]
Not just my antivirus but also my browser thinks its a trojan. If you put it in a zip file, it will escape browser detection and later I can turn off my antivirus and unzip and make exclusions.
Btw, good job on making these programs.

**Comment by Vili1** [comment]
or u can just go to ur downloads and press download this dangerous file anyway and yeah ;v or u can compile the code on ur computer and u dont have that problem

**Comment by Vili1** [comment]
if u need help add me on discord Vili#2690
