### ISSUE TITLE
YOU GAVE ME A VIRUS >>:((

### ISSUE THREAD

**Issue by KITKATKILLER67** [Vili1/Among-us-Free-Chat-unlocker#14]
why try give me virus??

**Comment by Vili1** [comment]
why are you on github if you are going to complain like a little child , or mayebe you are idk

**Comment by Vili1** [comment]
compile it oon your own computer and your anti virus wont complain about it

**Comment by KITKATKILLER67** [comment]
ok sir, but i have to reset my pc to get rid of it :(

**Comment by Vili1** [comment]
thats probably a windows bug
