### ISSUE TITLE
among us free chat unlocker not working

### ISSUE THREAD

**Issue by asdaeshndj** [Vili1/Among-us-Free-Chat-unlocker#15]
recently i was downloading among us v2021.6.30s and i started among us and launch among us chat unlocker and i test it its not working then i restarted the chat unlocker and its still not working so i try among us v2021.6.30e and it still same

**Comment by Vili1** [comment]
i will take a look

**Comment by Vili1** [comment]
have you tried closing everything with the name among us , except the game

**Comment by asdaeshndj** [comment]
yes

**Comment by Vili1** [comment]
did u manage to fix it ?
