### ISSUE TITLE
Post manual for these files

### ISSUE THREAD

**Issue by tedomedo** [Vili1/Among-us-Free-Chat-unlocker#18]
I don't have a clue what to do with these files. Should i move them to the folder where among us.exe is? Should i delete everything in \AppData\LocalLow\Innersloth\Among Us? 
Give me step-by-step guide. 

Edit: I've found among us 7.20e.zip with Free.Chat.Unlocker.EXE (press delete to enable chat) on https://www.youtube.com/watch?v=_0dGVx6tYE4 so i don't need help.

**Comment by tedomedo** [comment]
Yeah, that among us which i got in youtube is yours :) Thanks. 
What is source core for? I don't think it's needed for free chat unlocker. I didn't move it to the game folder and chat unlocker worked. 
I have a off-topic question: how to disable automatic randomizing name when the game is launched? My way is to open playerPrefs, change name, save, then right click this file and tick read only in preferences.

**Comment by Vili1** [comment]
the source code is if u want to build the application yourself, and about your question im not sure

**Comment by jmscreation** [comment]
@tedomedo 
I modified this program and added a change name feature. It actually does just that. It sets the username in playerPrefs, then makes the file readonly. Once the game is launched, the file is then set back to normal so you can change settings and such.
