### ISSUE TITLE
Minor issue with your pattern scan code

### ISSUE THREAD

**Issue by jmscreation** [Vili1/Among-us-Free-Chat-unlocker#19]
There's actually a possibility for this to fail when scanning the memory for a pattern match.

Given that in 4096 bytes per cache buffer, if the pattern lands at the end of the buffer, where the rest of the pattern match would otherwise be on the next chunk, this will fail to find the pattern.

**To fix this, you'll need to increment the bytes instead by the value of bytes read minus the size of the pattern match you are looking for less 1 byte.**

For example:

```cpp
...

size_t patternLength = strlen(mask);

...

else
{
	//advance to next chunk
	currentChunk = currentChunk + std::max(0, bytesRead - (patternLength - 1));
}

```

**In doing so, it allows the pattern match to "re-search" the end of the buffer including the starting bytes of the next chunk.**

(EDIT: I did test the example code and there is something wrong with it; I'm looking for a working solution)
(+ I found that the `VirtualProtectEx` was causing the crash. Removing this fixed the issue temporarily. It's possible the issue is due to a padding requirement for the function byte pointer.)

_Another side note:
the pattern match will greatly fail if it's greater than 4KB._

**Comment by jmscreation** [comment]
I would, except I ended up making so many changes that I ended up adding a Name Updater into this same application. So now it not only unlocks free chat, but it also forces the name to be set.

**Comment by jmscreation** [comment]
I would also need to do some research on how `VirtualProtectEx` and `VirtualQueryEx` works. It's not as simple to fix as I thought.

When I have time, I can piece together a much more robust solution. One that will also prevent crashing due to invalid/unaligned page pointer offsets.

**Comment by Vili1** [comment]
ada3ff0bd59daff2f9597650321d734f6bf440e9

**Comment by Vili1** [comment]
@jmscreation im sure that it can be done in a very simple way whenever u open the name edit feature in the game there should be a check somewhere to see if u could change the name etc... i just havent reversed the game that much nor i really have the motivation

**Comment by jmscreation** [comment]
I did try to find the check via the pattern match, but it was unsuccessful. I also don't have the time nor motivation to take on such a task at the moment.

**Comment by Vili1** [comment]
@jmscreation did u came up with a solution or something

**Comment by jmscreation** [comment]
An easy solution would be to just read 3 chunks at a time, and check for a pattern match within the 3 chunks, thereafter deleting the first chunk and adding 1 chunk to the end keeping it 3 chunks in total for the duration of the search.

I'm not sure why I didn't think of this as soon as I realized that an alignment was necessary.

**Comment by Vili1** [comment]
i mean its working fine rn so ye
