### ISSUE TITLE
The new release causes constant "You disconnected from the server" errors

### ISSUE THREAD

**Issue by Topkek-190** [Vili1/Among-us-Free-Chat-unlocker#20]
Using clean steam files with all instructions followed

**Comment by Vili1** [comment]
@Topkek-190 go from offline to a play as guest state here ive made a tutorial https://youtu.be/D5zzvgSodSs

**Comment by Topkek-190** [comment]
What version of Among Us are you using?

**Comment by Vili1** [comment]
try with  v2021.12.16s

**Comment by Vili1** [comment]
@Topkek-190 just in case press on play as a guest first then go in offline use the unlocker and then play as a guest again , might help

**Comment by Topkek-190** [comment]
Yeah, it works on 2021.12.16s, thanks

**Comment by Topkek-190** [comment]
It's definitely connected to the unlocker. When I join a lobby without the unlocked chat and name, the game ends normally, but when I unlock and join, the game gets stuck after imposter gets last kill

**Comment by Topkek-190** [comment]
@Vili1 The older release, 0.16 seems to work correctly functioning as intended. The problem seems to be the name changer

**Comment by Vili1** [comment]
@Topkek-190 yeh i agree thats a bug, i cant find a workaround tho

**Comment by Vili1** [comment]
maybe u should roll back the name unlocker, but the thing is that also removes the possibility of joining private rooms
