### ISSUE TITLE
"You must have an account to play online"

### ISSUE THREAD

**Issue by RandomDude78** [Vili1/Among-us-Free-Chat-unlocker#21]
Hi,

Whenever I try to play online after unlocking the name changer, The game says "The Among Us servers could not authenticate you. You must have an Among Us account to play online. (Guest account is okay!)". Here's how it looks like in-game:
![y](https://user-images.githubusercontent.com/88250218/151025589-1837ffb9-9015-4b91-9c56-5103483c9cc3.PNG)
If you're already trying to fix this, Then good luck bro!

**Comment by Vili1** [comment]
@RandomDude78 the whole trick is to go from an offline state of the game to play as guest heres a tutorial https://youtu.be/D5zzvgSodSs
