### ISSUE TITLE
Not working in the latest version of Among Us

### ISSUE THREAD

**Issue by axsandri** [Vili1/Among-us-Free-Chat-unlocker#22]
It does unlock the skins but free chat remains disabled

**Comment by Vili1** [comment]
i will fix it in a few days

**Comment by StopRussiaNOW** [comment]
When Will It Be Fixed

**Comment by Vili1** [comment]
when i have some free time probably tomorrow

**Comment by StopRussiaNOW** [comment]
ok

**Comment by StopRussiaNOW** [comment]
i have a question does your progress save if you uninstall among us?

**Comment by Vili1** [comment]
im not sure but i updated it
