### ISSUE TITLE
Cant unlock the freechat servers in the find servers tab

### ISSUE THREAD

**Issue by GuestTox** [Vili1/Among-us-Free-Chat-unlocker#28]
when i try to join a server with an ID, i can't join it because it asks me to either join a free chat server or quick chat so if i'm not signed in i can't use it
![image](https://user-images.githubusercontent.com/93429502/171227582-00d59ef5-6d92-499d-9b68-f45fed13ed4c.png)

**Comment by Vili1** [comment]
sadly i cant fix that issue, the only way ive found to fix it causes other issue like the game locks or it kicks u from the game, maybe u should host the games instead
