### ISSUE TITLE
Do you have free chat unlocker for 2022.3.29s?

### ISSUE THREAD

**Issue by tedomedo** [Vili1/Among-us-Free-Chat-unlocker#29]
I tried your newest .exe but i saw windows message on entire screen that this exe doesn't work. I have windows 10, I have cheat engine 7.4, so please try to create .dll for free chat unlocking.

**Comment by Vili1** [comment]
what error are u getting exactly

**Comment by tedomedo** [comment]
Before if wasn't error, just a message that .exe can't be launched, it was on screen with red color around. Right now i downloaded it again, i got warning from defender but i launched it and it worked. 
Can you create something to change name as guest?

**Comment by Vili1** [comment]
stop your anti virus, also the name changing feature had to me deleted because it was causing issues

**Comment by tedomedo** [comment]
I used Town of Us - it has free chat and name, but i wasn't able to kill online. I will use your tool.
