### ISSUE TITLE
Off-topic question (don't ban me, please): innersloth disabled playing as guest in the latest among us version

### ISSUE THREAD

**Issue by tedomedo** [Vili1/Among-us-Free-Chat-unlocker#31]
I don't know who to ask so i ask you. Please contact your github crewmates and try to find a way in order to play without account.

**Comment by tedomedo** [comment]
It isn't an issue. Among us versions from 2022.6. 21 on don't let us play as guest. Account is needed in order to play. Your free chat unlocker is used by us who play as guest - without account.

**Comment by Vili1** [comment]
hmm well i dont think that i can do anything about it
