### ISSUE TITLE
System Cannot find the path 

### ISSUE THREAD

**Issue by Rajbir98** [Vili1/Among-us-Free-Chat-unlocker#32]
![image](https://user-images.githubusercontent.com/84771149/178020582-9685cdf9-73ff-40c6-9ca2-fa1737e1dcc4.png)

**Comment by Vili1** [comment]
is that windows?
also try installing https://download.visualstudio.microsoft.com/download/pr/ed95ef9e-da02-4735-9064-bd1f7f69b6ed/CF92A10C62FFAB83B4A2168F5F9A05E5588023890B5C0CC7BA89ED71DA527B0F/VC_redist.x86.exe
