### ISSUE TITLE
Impossible to launch the app

### ISSUE THREAD

**Issue by SAB236YT** [Vili1/Among-us-Free-Chat-unlocker#33]
and yes i installed C++ (x64 bc i have x64)
please help

**Comment by Vili1** [comment]
install x86 bcs the application is 32bit

**Comment by Vili1** [comment]
also turn off windows defender or any other anti virus

**Comment by SAB236YT** [comment]
> install x86 bcs the application is 32bit

what is bcs? c++?

**Comment by Vili1** [comment]
the application isnt 64 bit its 32 so install x86
