### ISSUE TITLE
Cannot Open while opening among us

### ISSUE THREAD

**Issue by Gamfam** [Vili1/Among-us-Free-Chat-unlocker#35]
Hey U might be wondering if u read this thats the because i cant open the unlocker after opening the game is seeing this fix it plez

**Comment by Vili1** [comment]
what do you mean exactly

**Comment by Gamfam** [comment]
bro i litterally when open the AMOGUS i keep it on but then open the unlocker and exactly cannot work its just when open its just disappeard(sorry if cap i guess maybe it was mistake)

**Comment by Vili1** [comment]
wahat game version?
