### ISSUE TITLE
Doesn't Work For Town of Us

### ISSUE THREAD

**Issue by KH0DIIN** [Vili1/Among-us-Free-Chat-unlocker#4]
the application works only for normal among us, it doesn't work for the Town of Us Mod which is what everyone plays now so please make it work for the Town of Us aswell

**Comment by Vili1** [comment]
did u tried the second version from the downloads ?

**Comment by Vili1** [comment]
this one 
![image](https://user-images.githubusercontent.com/42891941/116637252-0b88aa00-a96c-11eb-99cb-6141c980ef63.png)

**Comment by KH0DIIN** [comment]
> did u tried the second version from the downloads ?

**Comment by KH0DIIN** [comment]
um sorry i closed by mistake, moving on yes i've tried the second one in the downloads and the chat didn't open and i was spamming the keybind "F1" and it didn't work at all even with both versions, so please try fixing that in the next update
