### ISSUE TITLE
why are you lying it is a virus

### ISSUE THREAD

**Issue by MarkoczekTV** [Vili1/Among-us-Free-Chat-unlocker#7]

**Comment by MarkoczekTV** [comment]
its working but its a virus

**Comment by MarkoczekTV** [comment]
also
now make old font bringer

**Comment by KH0DIIN** [comment]
i talked to him in discord and he gave me another way to unlock chat and it's way too easier

**Comment by KH0DIIN** [comment]
you can give me your discord tag and i'll screenshare how it works

**Comment by KH0DIIN** [comment]
and i'll show the way he gave me and it's way too easier you don't have to keep an application running 24/7 while you're playing the game

**Comment by Vili1** [comment]
both versions should work now :v
