### ISSUE TITLE
Not working for me

### ISSUE THREAD

**Issue by FUKU-00** [Vili1/Among-us-Free-Chat-unlocker#8]
I've even placed the exe within the among us directory. Tested Among us Version 2021.4.14s (with TheOtherRoles 2.5.1) and stock 2021.5.10s. Thats the printout. Nothing else happens:

`Among Us found successfully!`
`---------------------------------------------------------------------------`
`Free Chat Unlocker by Vili`
`---------------------------------------------------------------------------`

**Comment by MainframeSuper** [comment]
the old-ish file from Vili works!
free_chat**_both_**v2021.12.14
