### ISSUE TITLE
IDP.Generic

### ISSUE THREAD

**Issue by MainframeSuper** [Vili1/Among-us-Free-Chat-unlocker#9]
![image](https://user-images.githubusercontent.com/76067201/118019346-868f8e80-b376-11eb-8d40-8bfffb8be42b.png)
well this is sad. are you onto our passwords? Didnt happen anytime before. Just today.

**Comment by Vili1** [comment]
man i dont use anivirus softoware in general so yeh, u might want to turn off ur anti virus and download the latest version because i can tell that u have an old one plus its saying that its a virus because the program was made on my comuter and it isnt digitaly singed so yeh

**Comment by MainframeSuper** [comment]
oh ok thank you :)
im using the old one because its compatible with among us
You do a great job man!
